services:
  base:
    build:
      context: ./docker/base
      tags:
        - "ollama_app:base"
    image: ollama_app:base
    
  jupyter:
    build:
      context: ./docker/jupyter
      tags:
        - "ollama_jupyter:latest"
    init: true
    image: ollama_jupyter:latest
    ports:
      - "18888:8888" # Jupyter
    volumes:
      - .:/llama_kattis
    expose:
      - "8888"
    hostname: jupyter
    container_name: jupyter
    networks:
      - ollama_net

  ollama-a:
    container_name: ollama-a
    image: ollama/ollama
    volumes:
      - ../../ollama_models:/root/.ollama
    expose:
      - "11434"
    environment:
      OLLAMA_RUN_TIMEOUT: 600
      OLLAMA_REQUEST_TIMEOUT: 600
      OLLAMA_LOAD_TIMEOUT: 600
    networks:
      - ollama_net

  ollama-b:
    container_name: ollama-b
    image: ollama/ollama
    volumes:
      - ../../ollama_models:/root/.ollama
    expose:
      - "11434"
    environment:
      OLLAMA_RUN_TIMEOUT: 600
      OLLAMA_REQUEST_TIMEOUT: 600
      OLLAMA_LOAD_TIMEOUT: 600
    networks:
      - ollama_net

networks:
  ollama_net:
    name: ollama_net
    driver: bridge
